### ISSUE TITLE
Doesn't work with Antd 4.14+

### ISSUE THREAD

**Issue by jeanmatthieud** [SolidZORO/next-plugin-antd-less#42]
I used the package with Antd 4.13.1
After upgrading to Antd 4.14+ (or Antd 4.15+), the customization stopped working.

I have the latest plugin release (v1.0.8)
And next@10.1.3

My less file :
```less
// - Custom variables
@customer-color: #006FBA;
@customer-background-color: #FAFDFF;

// - Antd variables
@primary-color: @customer-color;
@link-color: @customer-color;
@heading-color: @customer-color;
@border-radius-base: 4px;
@layout-body-background: @customer-background-color;
@layout-sider-background: #FFFFFF;
@layout-header-background: #FFFFFF;
@layout-trigger-background: @customer-color;
@layout-header-color: @primary-color;
@alert-message-color: rgba(0, 0, 0, 0.85);

.ant-layout-header {
  border-bottom: 1px solid @primary-color;
}
```

My next.config.js file :
```js
const withAntdLess = require('next-plugin-antd-less');

module.exports = withAntdLess({
  lessVarsFilePath: './styles/antd.less',
  cssLoaderOptions: { },
  i18n: {
    locales: ['en', 'fr'],
    defaultLocale: 'fr',
  },
});
```
